explorer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('planninghistory/', include(('planninghistory.urls', 'planninghistory'), namespace='planninghistory')),
    path('plan/', include('plan.urls', namespace='plan')),
    path('', include(('explorerapp.urls', 'explorer'),namespace = 'explorer')),

]

explorerapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/<slug:slug>/', views.PlaceView.as_view(), name='place_detail'),
    path('places/', views.places_list, name='places_list'),
    path('<slug:slug>/', views.PlacesListByCategory.as_view(), name='places_list_by_category'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.urls import path
from . import views

app_name = 'plan'

urlpatterns = [
    path('', views.plan_detail, name='plan_detail'),
    path('add/<int:place_id>/',
         views.plan_add,
         name='plan_add'),
    path('remove/<int:place_id>/',
         views.plan_remove,
         name='plan_remove'),
    ]

planninghistory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.event_create, name='event_create'),
    path('events/', views.EventHistory.as_view(), name='event_history')
]

plan/forms.py
from django import forms
from bootstrap_datepicker_plus import DateTimePickerInput


class PlanAddPlaceForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class EventAdd(forms.Form):
    start_date = forms.DateTimeField(widget=DateTimePickerInput(), initial="Data rozpoczęcia")
    end_date = forms.DateTimeField(widget=DateTimePickerInput(), required=False)

plan/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from explorerapp.models import Place
from .plan import Plan
from .forms import PlanAddPlaceForm


@require_POST
def plan_add(request, place_id):
    plan = Plan(request)
    place = get_object_or_404(Place, id=place_id)
    plan_form = PlanAddPlaceForm(request.POST)
    if plan_form.is_valid():
        cd = plan_form.cleaned_data
        plan.add(place=place)
    else:
        return render(request, 'explorer/place_detail.html', {'place': place, 'plan_form': plan_form})
    return redirect('plan:plan_detail')


def plan_remove(request, place_id):
    plan = Plan(request)
    place = get_object_or_404(Place, id=place_id)
    plan.remove(place)
    return redirect('plan:plan_detail')


def plan_detail(request):
    plan = Plan(request)
    context = {'plan': plan}
    return render(request, 'plan/detail.html', context)

plan/templates/plan/detail.html
{% extends "explorer/base.html" %}
{% load static %}

{% block title %}
    Twój Plan
{% endblock %}

{% block content %}
  {% load static %}
  {% load bootstrap4 %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
  <h1>Twój plan</h1>
  <table class="table table-bordered table-striped table-dark">
      <thead class="thead-dark">
        <tr>

            <th>Miejsce</th>
            <th>Adres</th>
            <th>Cena</th>
            <th></th>
        </tr>
      </thead>
      <tbody>
          {% for item in plan %}
            {% with place=item.place %}
              <tr>

                  <td>
                      <a href="{{ place.get_absolute_url }}">{{ place.name }}</a>
                  </td>
                  <td>
                      {{ place.address }}
                  </td>
                  <td class="num">
                      {{ item.cost }}PLN
                  </td>
                  <td>
                      <a href="{% url 'plan:plan_remove' place.id %}">Usuń</a>
                  </td>
              </tr>
            {% endwith %}
          {% endfor %}
        <tr class="total">
            <td style="font-weight:bold">Całkowity koszt</td>
            <td colspan="1"></td>
            <td style="font-weight:bold" class="num">{{ plan.get_total_price }}PLN</td>
        </tr>
      </tbody>
  </table>
  {% if user.is_authenticated %}
  <p class="text-left">
    <a href="{% url 'planninghistory:event_create' %}" class="btn btn-success">Zapisz plan</a>
  </p>
  {% endif %}
  <p class="text-right">
      <a href="{% url 'explorer:places_list' %}" class="btn btn-success" >Kontynuuj planowanie</a>
  </p>
{% endblock %}