explorer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('planninghistory/', include(('planninghistory.urls', 'planninghistory'), namespace='planninghistory')),
    path('plan/', include('plan.urls', namespace='plan')),
    path('', include(('explorerapp.urls', 'explorer'),namespace = 'explorer')),

]

explorerapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/<slug:slug>/', views.PlaceView.as_view(), name='place_detail'),
    path('places/', views.places_list, name='places_list'),
    path('<slug:slug>/', views.PlacesListByCategory.as_view(), name='places_list_by_category'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.urls import path
from . import views

app_name = 'plan'

urlpatterns = [
    path('', views.plan_detail, name='plan_detail'),
    path('add/<int:place_id>/',
         views.plan_add,
         name='plan_add'),
    path('remove/<int:place_id>/',
         views.plan_remove,
         name='plan_remove'),
    ]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    # Login page,
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='explorer/index.html'), name="logout"),
    path('register/',views.register, name='register'),
    path('userprofile/', views.profile, name="profile"),
    path('editprofile/', views.edit_profile, name="edit_profile"),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    avatar = models.ImageField(
        upload_to='static/img',
        default='no-image.png',
        blank=True
    )
    first_name = models.CharField(max_length=255, default='')
    last_name = models.CharField(max_length=255, default='')
    email = models.EmailField(default='none@email.com')
    birth_date = models.DateField(default='1999-12-31')
    bio = models.TextField(default='')
    city = models.CharField(max_length=255, default='')
    state = models.CharField(max_length=255, default='')
    country = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import Profile


class UserProfileForm(forms.ModelForm):
    bio = forms.CharField(required=False, widget=forms.Textarea)

    class Meta:
        model = Profile
        fields = [
            'avatar',
            'first_name',
            'last_name',
            'email',
            'birth_date',
            'bio',
            'city',
            'state',
            'country',
        ]
        labels = {
            'first_name': _('Imię'),
            'last_name': _('Nazwisko'),
            'birth_date': _('Data urodzenia'),
            'city': _('Miasto'),
            'state': _('Województwo'),
            'country': _('Kraj')}

    def clean(self):
        cleaned_data = super(UserProfileForm, self).clean()
        bio = cleaned_data.get("bio")


        if len(bio) < 10:
            raise forms.ValidationError(
                "Bio must be 10 characters or longer!"
            )

users/views.py
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required


from .models import Profile
from .forms import UserProfileForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('explorer:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

@login_required
def profile(request):
    """Display User Profile"""
    profile = request.user.profile
    return render(request, 'users/user_profile.html', {
        'profile': profile
    })

@login_required
def edit_profile(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    form = UserProfileForm(instance=profile)

    if request.method == 'POST':
        form = UserProfileForm(instance=profile, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated the Profile Successfully!")
            return HttpResponseRedirect(reverse('users:profile'))

    return render(request, 'users/edit_profile.html', {
        'form': form
    })

users/templates/users/edit_profile.html
{% extends "explorer/base.html"%}
{% load static from staticfiles %}

{% block header %}Użytkownik | {{ user }} {{ super }}{% endblock %}

{% block content %}
    <div class="grid-100">
        <h1>Edytuj Profil</h1>
        <form method="POST" actions="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="button" value="Zapisz" />
        </form>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends "explorer/base.html" %}
{% load bootstrap3 %}

{% block header%}
  <h2> Log in to your account.</h2>
{% endblock header %}

{% block content %}
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Zaloguj się</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'explorer:index' %}"/>
  </form>
{% endblock content %}

users/templates/users/register.html
{% extends "explorer/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h1>Rejestracja</h1>
{% endblock header %}


{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
	<button name="submit" class="btn btn-primary">Zarejestruj się</button>
	{% endbuttons %}
	<input type="hidden" name="next" value="{% url 'explorer:index' %}" />

  </form>
{% endblock content %}

users/templates/users/user_profile.html
{% extends "explorer/base.html"%}
{% load static %}
{% load bootstrap3 %}

{% block header %}Użytkownik | {{ user }} {{ super }}{% endblock %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

    <h1>Profil</h1>
    <img class="img-thumbnail" id="placeimg" style="float:left; margin:25px; width:200px; height:220px;" src="{% if profile.avatar %}{{ profile.avatar.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
    <div class="grid-20">

    </div>

    <div class="container">
          <div class="row" >
            <div class="col-md-6" id="profile">

                {% if not profile.first_name %}
                    <p>Profil jest pusty. Uzupełnij profil</p>
                    <a href="{% url 'users:edit_profile' %}">Dodaj elementy do profilu</a>
                {% else %}
                    <div >

                        <p><span class="underline">Imię</span>: {{ profile.first_name }}</p>
                        <p><span class="underline">Nazwisko</span>: {{ profile.last_name }}</p>
                        <p><span class="underline">Data urodzenia</span>: {{ profile.birth_date }}</p>
                        <p><span class="underline">Email</span>: {{ profile.email }}</p>
                        <p><span class="underline">Miasto</span>: {{ profile.city }}</p>
                        <p><span class="underline">Województwo</span>: {{ profile.state }}</p>
                        <p><span class="underline">Kraj</span>: {{ profile.country }}</p>
                    </div>
                    <div >
                        <p><span class="underline">Bio</span>: {{ profile.bio|safe }}</p>
                    </div>
                    <a class="btn btn-primary" href="{% url 'users:edit_profile' %}">Edytuj Profil</a></li>

                {% endif %}
            </div>
            <div class="col-md-3" id="information-table" >
            </div>
          </div>
    </div>
{% endblock %}