explorer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('planninghistory/', include(('planninghistory.urls', 'planninghistory'), namespace='planninghistory')),
    path('plan/', include('plan.urls', namespace='plan')),
    path('', include(('explorerapp.urls', 'explorer'),namespace = 'explorer')),

]

explorerapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/<slug:slug>/', views.PlaceView.as_view(), name='place_detail'),
    path('places/', views.places_list, name='places_list'),
    path('<slug:slug>/', views.PlacesListByCategory.as_view(), name='places_list_by_category'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.urls import path
from . import views

app_name = 'plan'

urlpatterns = [
    path('', views.plan_detail, name='plan_detail'),
    path('add/<int:place_id>/',
         views.plan_add,
         name='plan_add'),
    path('remove/<int:place_id>/',
         views.plan_remove,
         name='plan_remove'),
    ]

planninghistory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.event_create, name='event_create'),
    path('events/', views.EventHistory.as_view(), name='event_history')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    # Login page,
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='explorer/index.html'), name="logout"),
    path('register/',views.register, name='register'),
    path('userprofile/', views.profile, name="profile"),
    path('editprofile/', views.edit_profile, name="edit_profile"),
    ]

explorerapp/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.urls import reverse
from django.contrib.auth.models import User


class City(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('explorer:places_list_by_category', args=[self.slug])


class Address(models.Model):
    street = models.CharField(max_length=60)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    location_number = models.CharField(max_length=10, blank=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=8, null=True, blank=True)
    length = models.DecimalField(max_digits=11, decimal_places=8, null=True, blank=True)

    def __str__(self):
        address = (self.street, self.location_number, self.city.name)
        return ' '.join(address)


class Place(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField()
    category = models.ForeignKey(Category, related_name='places', on_delete=models.CASCADE)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='images/%Y/%m/%d', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True)
    sum_of_rating = models.DecimalField(max_digits=9, decimal_places=2, default=5)
    num_of_ratings = models.IntegerField(default=1)
    tags = TaggableManager()

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('explorer:place_detail', args=[self.id, self.slug])


class Comment(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    rate = models.IntegerField()

explorerapp/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import Comment

class RatingForm(forms.Form):
    OPTIONS = [
        (1, 'Okropna Nuda!'),
        (2, 'Nieciekawe'),
        (3, 'Można obejrzeć'),
        (4, 'Ciekawe'),
        (5, 'Świetne!')
    ]
    Rating = forms.ChoiceField(widget=forms.RadioSelect, choices=OPTIONS)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        labels = {
            'name': _('Twój nick'),
            'body': _('Treść')}

explorerapp/views.py
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.views.generic import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView

from .models import Category, Place, Rating
from .forms import RatingForm, CommentForm
from .filters import PlaceFilter


def index(request):
    # Strona glowna.
    places = Place.objects.all()[:10]
    context = {'places': places}
    return render(request, 'explorer/index.html', context)


class PlaceView(View):
    template_name = 'explorer/place_detail.html'

    def place_detail(self):
        place = get_object_or_404(Place, id=self.kwargs['id'], slug=self.kwargs['slug'])
        return place

    def comments_get(self):
        place = get_object_or_404(Place, id=self.kwargs['id'], slug=self.kwargs['slug'])
        comments = place.comments.filter(active=True)
        return comments

    def get_rating(self, request):
        place = self.place_detail()
        rating = Rating.objects.filter(user=request.user, place=place)
        return rating

    def get_context_data(self,  **kwargs):

        kwargs['place'] = self.place_detail()
        kwargs['comments'] = self.comments_get()
        if 'rating_form' not in kwargs:
            kwargs['rating_form'] = RatingForm()
        if 'comment_form' not in kwargs:
            kwargs['comment_form'] = CommentForm()
        return kwargs

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, *args, **kwargs):
        ctxt = {}

        if 'rating' in request.POST:
            rating_form = RatingForm(request.POST)

            if rating_form.is_valid():
                place = self.place_detail()
                rate = int(rating_form.cleaned_data['Rating'])
                place.sum_of_rating += rate
                place.num_of_ratings += 1

                if self.get_rating(request):
                    old_rate = Rating.objects.filter(user=request.user, place=place)
                    place.num_of_ratings -= 1
                    place.sum_of_rating -= old_rate[0].rate
                    old_rate.delete()

                Rating.objects.create(user=request.user, place=place, rate=rate)
                place.save()
                return redirect('explorer:place_detail', id=self.kwargs['id'], slug=self.kwargs['slug'])
            else:

                ctxt['rating_form'] = rating_form

        elif 'comment' in request.POST:
            comment_form = CommentForm(request.POST)

            if comment_form.is_valid():
                new_comment = comment_form.save(commit=False)
                place = self.place_detail()
                new_comment.place = place
                new_comment.save()

                return redirect('explorer:place_detail', id=self.kwargs['id'], slug=self.kwargs['slug'])
            else:
                ctxt['comment_form'] = comment_form
        return render(request, self.template_name, self.get_context_data(**ctxt))


class PlacesListByCategory(ListView):
    model = Category
    template_name = 'explorer/category_list.html'
    context_object_name = 'category'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['places'] = Place.objects.filter(category__slug=self.kwargs['slug'])
        return context


class PlacesList(ListView):
    model = Place
    template_name = 'explorer/places_list.html'
    context_object_name = 'places'
    paginate_by = 5
    queryset = Place.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PlaceFilter(self.request.GET,  queryset=self.get_queryset())

        return context


def places_list(request):
    page_list = Place.objects.all()
    place_filter = PlaceFilter(request.GET, queryset=page_list)
    place_list = place_filter.qs

    paginator = Paginator(place_list, 4)
    page = request.GET.get('page', 1)
    try:
        places = paginator.page(page)
    except PageNotAnInteger:
        places = paginator.page(1)
    except EmptyPage:
        places = paginator.page(paginator.num_pages )

    context = {'paginator':paginator, 'filter':place_filter, 'places':places}
    return render(request, 'explorer/places_list.html', context)

explorerapp/templates/explorer/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en"> 
  <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Explorer</title>
	{% bootstrap_css %}
	{% bootstrap_javascript %}
  </head>
<body >
    <nav class="navbar navbar-default navbar-static-top">
	  <div class="container">

	    <div class="navbar-header">
		  <button type="button" class="navbar-toggle collapse"
		    data-toogle="collapse" data-target="#navbar"
			aria-expanded="false" aria-controls="navbar">
	      </button>
		  <a class="navbar-brand" href="{% url 'explorer:index' %}">Strona Główna</a>
		  <ul class="nav navbar-nav">
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
                <p class="navbar-text navbar-left">Witaj <a href="#" class="navbar-link">, {{ user.username }}.</a></p>
				<li><a href="{% url 'users:logout' %}">Wyloguj się</a></li>
				<li><a href="{% url 'explorer:places_list' %}">Lista miejsc</a></li>
                <li><a href="{% url 'planninghistory:event_history' %}">Historia Planów</a></li>
                <li><a href="{% url 'users:profile' %}">Twój Profil</a></li>
				{% else %}
				<li><a href="{% url 'users:register' %}">Zarejestruj się</a></li>
				<li><a href="{% url 'users:login' %}">Zaloguj się</a></li>
				<li><a href="{% url 'explorer:places_list' %}">Lista miejsc</a></li>
				{% endif %}
                <p class="navbar-text navbar-right">
                    {% with total_items=plan|length %}
                      {% if plan|length > 0 %}
                        Twój Plan:
                        <a href="{% url 'plan:plan_detail' %}">
                            {{ total_items }} Pozycje
                            {{ plan.get_total_price }}PLN
                        </a>
                      {% else %}
                        Twój plan jest pusty
                      {% endif %}
                    {% endwith %} </p>
                <li>
                </li>
			</ul>
		  </ul>
          <div class="form-inline my-2 my-lg-0">
          </div>
        </div><!--/.nav-collapse -->
	  </div>
	</nav>
	<div class="container">
	  <div class="page-header">
	    {% block header %}{% endblock header %}
      </div>
    <div id="subheader">
    </div>
	  <div>
	    {% block content %}{% endblock content %}
      </div>

	</div> <!-- /container -->
    <footer style="width:100%; height:5vw;"></footer>
  </body>
</html>



explorerapp/templates/explorer/category_list.html
{% extends "explorer/base.html" %}

{% block title %}
  {{ category.name }}
{% endblock %}

{% block content %}
  {% load static %}
  {% load mathfilters %}
  {% load bootstrap3 %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/places_list.css' %}">
    {% for place in places %}
        <div class="place">
            <a class="title" href="{{ place.get_absolute_url }}"> {{ place.name }} </a>
            <a  href="{{ place.get_absolute_url }}">  <img class="image" src="{% if place.image %}{{ place.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"> </a>
            <div class="desc" >{{ place.description | truncatechars:300 }} <a href="{{place.get_absolute_url}}">(czytaj dalej)</a> </div>
            <form action="{% url 'plan:plan_add' place.id %}"  method="post" class="plan_form" >
                {% csrf_token %}
                {{ plan_form.start_date.errors }}
                <p style="float:left">{{ plan_form.end_date.errors }}</p>
                <p>{{ plan_form.start_date }}</p>
                <p>{{ plan_form.end_date }}</p>
                <input class="btn btn-primary btn-lg"  name="plan" type="submit" value="Dodaj miejsce" style="float:right" ></input>
            </form>
        </div>
    {% endfor %}

{% endblock %}

explorerapp/templates/explorer/index.html
{% extends "explorer/base.html"%}

{% block header %}
  {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
  <div  class="maintop">
    <h1 class="maintop">Witaj Podróżniku </br><a  href="{% url 'explorer:places_list' %}">Zaplanuj Podróż</a> </h1>
  </div>
{% endblock header %}

{% block content %}
    <div id="main" class="place-list">
    {% for place in places %}
      <div class="place">
        <a href="{{ place.get_absolute_url }}">
          <img  src="{% if place.image %}{{ place.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
      </div>
    {% endfor %}
    </div>

{% endblock content %}

explorerapp/templates/explorer/pagination.html
{% if places.has_other_pages %}
        <ul class="pagination">
    {% if places.has_previous %}
      <li><a href="?page={{ places.previous_page_number }}">&laquo;</a></li>
    {% else %}
     <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
    {% for i in places.paginator.page_range %}
      {% if places.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)
     </span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if places.has_next %}
      <li><a href="?page={{ places.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>

{%  endif %}

explorerapp/templates/explorer/place_detail.html
{% extends "explorer/base.html" %}

{% block title %}
  {{ place.name }}
{% endblock %}

{% block content %}
  {% load static %}
  {% load mathfilters %}
  {% load bootstrap3 %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/place_detail.css' %}">
        <div class="container">
          <div class="row" >
            <div class="col-md-9" style="">
                <img id="placeimg" style="float:right; margin:25px" src="{% if place.image %}{{ place.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                <div >
                    <h2 style="text-shadow: 2px 2px black;">{{ place.name }}</h2>
                      <h4><a href="{{ place.category.get_absolute_url }}">{{ place.category }}</a></h4>
                      <p class="tags">Tags: {{ place.tags.all|join:", " }}</p>
                <div id="description" class="description">
                      {{ place.description|linebreaks }}
                </div>


                </div>


            </div>
            <div class="col-md-3" id="information-table" >
                <h4 class="place-name">{{ place.name }}</h4>
                <table style="background-color:white;">
                    <tr >
                        <th>Adres:</th>
                        <td>{{place.address.city }} {{ place.address.street }}, {{place.address.location_number }}</td>

                    </tr>
                    <tr>
                        <th>Cena:</th>
                        <td>{{ place.cost }} PLN</td>
                    </tr>
                    <tr>
                        <th>Typ atrakcji: </th>
                        <td>{{ place.category }}</td>
                    </tr>
                    <tr>
                        <th>Data powstania: </th>
                        <td>{{ place.creation_date}} rok</td>
                    </tr>
                    <tr>
                        <th>Ocena Użytkowników:</th>
                        <td>{{ place.sum_of_rating|div:place.num_of_ratings |floatformat }} ({{ place.num_of_ratings }} ocen)</td>
                    </tr>
                </table>
                <br>
                {{ plan_form.media }}
                <form action="{% url 'plan:plan_add' place.id %}"  method="post" class="plan_form" >
                    {% csrf_token %}
                    {{ plan_form.start_date.errors }}
                    <p style="float:left">{{ plan_form.end_date.errors }}</p>
                    <p>{{ plan_form.start_date }}</p>
                    <p>{{ plan_form.end_date }}</p>
                    <input class="btn btn-primary btn-lg btn-block"  name="plan" type="submit" value="Dodaj miejsce" style="float:right" ></input>
                </form>
            </div>
          </div>

          <div class="row" >

              <div class="col-md-9" style="padding-top:60px;">
              <hr class="hline" >
                  {% with comments.count as total_comments %}
                    <h2>
                        {{ total_comments }} comment{{ total_comments|pluralize }}
                    </h2>
                  {% endwith %}
                  {% for comment in comments %}
                    <div class="comment">
                        <hr class="hline">
                        <p class="info">
                            Comment {{ forloop.counter }} by {{ comment.name }}
                            </br>
                            {{ comment.created }}
                        </p>
                    {{ comment.body|linebreaks }}
                    </div>
                  {% empty %}
                    <p>Nie ma komentarzy</p>
                  {% endfor %}
                  <hr class="hline">
                  <form  method="post" style="color:black">
                    {% csrf_token %}
                    <div class="comment_form">
                      <div class="comment_field">Twoja Nazwa </div>  {{ comment_form.name }}
                      <div class="comment_field">E-mail </div>{{ comment_form.email }}
                      <div class="comment_field">Treść </div>{{ comment_form.body }}
                    </div>
                    <input class="comment_btn" name="comment" type="submit" value="Prześlij Komentarz" ></input>
                </form>
              </div>
              {% if user.is_authenticated %}
              <div class="col-md-3" >
                <div>
                  <h3 class="rating_form" style="text-align: center" >Oceń To Miejsce</h3>
                    <form  method="post" class="rating_form" >
                        {% csrf_token %}
                        {% for hidden_field in rating_form.hidden_fields %}
                            {{ hidden_field.errors }}
                            {{ hidden_field }}
                        {% endfor %}
                        {% for field in rating_form.visible_fields %}
                              {{ field.errors }}
                              {{ field }}
                              {{ field.help_text }}
                        {% endfor %}
                        <input class="rating_btn"  name="rating" type="submit" value="Prześlij Ocenę" style="float:right" ></input>
                    </form>
                </div>
              </div>
              {% endif %}
          </div>
        </div>
    {% if messages %}
        <ul>
           {% for message in messages %}
               <li>{{ message }}</li>
           {% endfor %}
        </ul>
    {% endif %}


{% endblock %}

explorerapp/templates/explorer/places_list.html
{% extends "explorer/base.html" %}
{% block title %}
{% endblock %}

{% block content %}
  {% load static %}
  {% load bootstrap3 %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/places_list.css' %}">
  <div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="gallery">

              {% for place in places %}
                  <div class="place">
                    <a class="title" href="{{ place.get_absolute_url }}"> {{ place.name }} </a>
                    <a  href="{{ place.get_absolute_url }}">  <img class="image" src="{% if place.image %}{{ place.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"> </a>
                    <div class="desc" >{{ place.description | truncatechars:300 }} <a href="{{place.get_absolute_url}}">(czytaj dalej)</a> </div>
                    <form action="{% url 'plan:plan_add' place.id %}"  method="post" class="plan_form" >
                    {% csrf_token %}
                    {{ plan_form.start_date.errors }}
                    <p style="float:left">{{ plan_form.end_date.errors }}</p>
                    <p>{{ plan_form.start_date }}</p>
                    <p>{{ plan_form.end_date }}</p>
                    <input class="btn btn-primary btn-lg"  name="plan" type="submit" value="Dodaj miejsce" style="float:right" ></input>
                </form>
                  </div>
              {% endfor %}

            </div>
            <div class="pagination">
                {% include "explorer/pagination.html" %}
            </div>

        </div>

        <div class="col-md-4">

            <form class="filter" method="GET">
                <div class="name">Nazwa</div> {{ filter.form.name }}
                <div class="name">Miasto</div> {{ filter.form.address__city }}
                <div class="name">Koszt mniejszy niż</div> {{ filter.form.cost__lt }}
                <div class="name">Koszt większy niż</div> {{ filter.form.cost__gt }}
                <div class="name">Kategoria</div> {{ filter.form.category}}
                <br/><br/>
                <button  type="submit" class="btn btn-primary" >Filtruj</button>
            </form>
        </div>
    </div>
  </div>

{% endblock %}